server:
  port: 1234

spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@127.0.0.1:1521:xe
    username: msa2
    password: msa2
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true
      properties:
        hibernate:
          format_sql: true
          use_sql_comments: true
          show_sql: true
        org:
          hibernate:
            SQL:
              dialect: org.hibernate.dialect.Oracle12cDialect

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

upload:
  path: C:/back_MSA/project/rest-area/devsculpt/src/main/resources/static/upload
