server:
  port: 8597
  tomcat:
    max-http-form-post-size: 10GB

spring:
  application:
    name: redis-test
  data:
    redis:
      host: 192.168.0.147
      port: 6379
      password: test1234
#  storage:
#    location: C:/back_msa/source
#    webLocation: /uploads
  sql:
    init:
      encoding: UTF-8
      #resources? ??? data.sql?? ??? sql?? ??
      mode: always
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@127.0.0.1:49160:xe
    username: mail
    password: mail

  jpa:
    show-sql: true
    hibernate:
#      ddl-auto: create
      ddl-auto: none
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true




  mail:
    host: smtp.naver.com
    port: 465
    username: rururia_@naver.com
    password: 859752560!djsntm
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true

  servlet:
    multipart:
      max-file-size: 10GB
      max-request-size: 10GB
      location: /Users/npc/Desktop/testimg


  Post: /v1/payment/approve
  Host: kapi.kakao.com
  Authorization: KakaoAK ${SERVICE_APP_ADMIN_KEY}
  Content-type: application/x-www-form-urlencoded;charset=utf-8




#  security:
#    oauth2:
#      client:
#        provider:
#          naver:
#            authorization-uri: https://nid.naver.com/oauth2.0/authorize
#            token-uri: https://nid.naver.com/oauth2.0/token
#            user-info-uri: https://openapi.naver.com/v1/nid/me
#            user-name-attribute: response
#          kakao:
#            authorization-uri: https://kauth.kakao.com/oauth/authorize
#            token-uri: https://kauth.kakao.com/oauth/token
#            user-info-uri: https://kapi.kakao.com/v2/user/me
#            user-name-attribute: id
#
#        registration:
#          google:
#            clientId: 82414011721-j2r3rgqjcnu4jatigansskp5flmd84gm.apps.googleusercontent.com
#            clientSecret: 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
#            redirect-uri: http://localhost:8597
#            scope:
#              - email
#              - profile
#
#          naver:
#            clientId: CoA22y4PyHoQ1WFbZkri
#            client-secret: JLKOYbO7Jz
#            redirect-uri: http://localhost:8080/login/oauth2/code/naver
#            authorization-grant-type: authorization_code
#            scope:
#              - name
#              - email
#              - profile_image
#            client-name: Naver
#
#          kakao:
#            clientId: d2f35f1434bf560a2fd936fa6e05eddd
#            client-secret: UO3tU2N9El43xIEO9pSCHXobm7tfRjhv
#            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
#            authorization-grant-type: authorization_code
#            scope:
#              - profile_nickname
#              - account_email
#              - profile_image
#            client-name: Kakao
#            client-authentication-method: POST


logging:
  level:
    org:
      hibernate:
        sql: debug
        type:
          descriptor:
            sql: trace

jwt:
  header: Authorization
  secret: Q4NSl604sgyHJj1qwEkR3ycUeR4uUAt7WJraD7EN3O9DVM4yyYuHxMEbSF4XXyYJkal13eqgB0F7Bq4H
  token-validity-in-second: 86400


